version: "3.9"


services:
  mosquitto:
    image: eclipse-mosquitto:latest
    volumes:
      - /efs/mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf        
    ports:
      - "1883:1883"
    networks:
      - conteneurs
    deploy:
      replicas: 2
      restart_policy:
        condition: any

  influxdb:
    image: influxdb:latest 
    ports:
      - "8086:8086"
    env_file:
      - influxdb.env
    networks:
      - conteneurs
    volumes:
      - /efs/db:/var/lib/influxdb
    deploy:
      replicas: 2
      restart_policy:
        condition: any
 
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    env_file:
      - influxdb.env
    networks:
      - conteneurs
    volumes:
      - /efs/grafana/lib:/var/lib/grafana
      - /efs/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - /efs/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
    depends_on:
      - influxdb
    deploy:
      replicas: 2
      restart_policy:
        condition: any
  
  mqttsubscriber:
    image: etiennetriomphe/projetconteneurisationmqttsubscriber:1.0.1
    depends_on:
      - mosquitto
    networks:
      - conteneurs
    deploy:
      replicas: 2
      restart_policy:
        condition: any


  mqttpublisher:
    image: etiennetriomphe/projetconteneurisationmqttpublisher:1.0.0
    depends_on:
      - mosquitto
    networks:
      - conteneurs
    deploy:
      replicas: 2
      restart_policy:
        condition: any



networks:
  conteneurs:
    attachable: true
    

