apiVersion: 1

deleteDatasources:
  - name: Influxdb_flux
    orgId: 1

datasources:
  - name: Influxdb_flux
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    orgId: 1
    secureJsonData:
      token: $DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
    jsonData:
      version: Flux
      organization: grandlyon
      defaultBucket: grandlyon-data
      tlsSkipVerify: true
