{
 "title": "Eau potable du Grand Lyon",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Volumes d'eau produits (m³)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "targets": [
    {
     "query": "from(bucket:\"grandlyon-data\")\r\n    |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n    |> filter(fn: (r) => r._field == \"volumes_produits\")"
    }
   ]
  },
  {
   "title": "Volumes d'eau achetés (m³)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "targets": [
    {
     "query": "from(bucket:\"grandlyon-data\")\r\n    |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n    |> filter(fn: (r) => r._field == \"volumes_achetes\")"
    }
   ]
  },
  {
   "title": "Volumes d'eau introduits (m³)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "targets": [
    {
     "query": "from(bucket:\"grandlyon-data\")\r\n    |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n    |> filter(fn: (r) => r._field == \"volumes_introduits\")"
    }
   ]
  },
  {
   "title": "Volumes d'eau vendus (m³)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "targets": [
    {
     "query": "from(bucket:\"grandlyon-data\")\r\n    |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n    |> filter(fn: (r) => r._field == \"volumes_vendus\")"
    }
   ]
  },
  {
   "title": "Volumes d'eau perdus (m³)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "targets": [
    {
     "query": "from(bucket:\"grandlyon-data\")\r\n    |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n    |> filter(fn: (r) => r._field == \"volumes_perdus\")"
    }
   ]
  },
  {
   "title": "Volumes d'eau consommés (m³)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "targets": [
    {
     "query": "from(bucket:\"grandlyon-data\")\r\n    |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n    |> filter(fn: (r) => r._field == \"volumes_consommes\")"
    }
   ]
  }
 ]
}